version: "3.8"

services:
  app:
    build: .
    container_name: todo_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: todo_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p123456"]
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: todo_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
